SELECT i.ItemNo, i.PartNo
FROM
    items.db i

/*_FQBMODEL
eAGLdkksSXRKLE6N5eUKDvSxNTQ2tTQ1NjMyNOLlig5JTMpJLQbKZNpmlqTmFuulJOkYmoKQkYEBkDIAqnEvykwBqjCw9QSq8MvXyQRSYIWZOoY6BmDIy2VoG5BYVIJLNtonMy8bZA0AvfwmZQ==
_FQBEND*/
