// CodeGear C++Builder
// Copyright (c) 1995, 2017 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'dclfrxIntIOIndy26.dpk' rev: 33.00 (Windows)

#ifndef Dclfrxintioindy26HPP
#define Dclfrxintioindy26HPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#pragma pack(push,8)
#include <System.hpp>	// (rtl)
#include <SysInit.hpp>
#include <frxRegIntIOIndy.hpp>
#include <System.UITypes.hpp>	// (rtl)
#include <Winapi.Windows.hpp>	// (rtl)
#include <Winapi.PsAPI.hpp>	// (rtl)
#include <System.Character.hpp>	// (rtl)
#include <System.Internal.ExcUtils.hpp>	// (rtl)
#include <System.SysUtils.hpp>	// (rtl)
#include <System.VarUtils.hpp>	// (rtl)
#include <System.Variants.hpp>	// (rtl)
#include <System.Math.hpp>	// (rtl)
#include <System.Rtti.hpp>	// (rtl)
#include <System.TypInfo.hpp>	// (rtl)
#include <System.Generics.Defaults.hpp>	// (rtl)
#include <System.Classes.hpp>	// (rtl)
#include <System.TimeSpan.hpp>	// (rtl)
#include <System.DateUtils.hpp>	// (rtl)
#include <System.IOUtils.hpp>	// (rtl)
#include <System.IniFiles.hpp>	// (rtl)
#include <System.Win.Registry.hpp>	// (rtl)
#include <System.UIConsts.hpp>	// (rtl)
#include <Vcl.Graphics.hpp>	// (vcl)
#include <System.Messaging.hpp>	// (rtl)
#include <System.Actions.hpp>	// (rtl)
#include <Vcl.ActnList.hpp>	// (vcl)
#include <System.HelpIntfs.hpp>	// (rtl)
#include <System.SyncObjs.hpp>	// (rtl)
#include <Winapi.UxTheme.hpp>	// (rtl)
#include <Vcl.GraphUtil.hpp>	// (vcl)
#include <Vcl.StdCtrls.hpp>	// (vcl)
#include <Winapi.ShellAPI.hpp>	// (rtl)
#include <Vcl.Printers.hpp>	// (vcl)
#include <Vcl.Clipbrd.hpp>	// (vcl)
#include <Vcl.ComCtrls.hpp>	// (vcl)
#include <Vcl.Dialogs.hpp>	// (vcl)
#include <Vcl.ExtCtrls.hpp>	// (vcl)
#include <Vcl.Themes.hpp>	// (vcl)
#include <System.AnsiStrings.hpp>	// (rtl)
#include <System.Win.ComObj.hpp>	// (rtl)
#include <Winapi.FlatSB.hpp>	// (rtl)
#include <Vcl.Forms.hpp>	// (vcl)
#include <Vcl.Menus.hpp>	// (vcl)
#include <Winapi.MsCTF.hpp>	// (rtl)
#include <Vcl.Controls.hpp>	// (vcl)
#include <IDEMessages.hpp>	// (designide)
#include <Vcl.CaptionedDockTree.hpp>	// (vcl)
#include <Vcl.DockTabSet.hpp>	// (vcl)
#include <Vcl.Grids.hpp>	// (vcl)
#include <Vcl.CategoryButtons.hpp>	// (vcl)
#include <Vcl.ButtonGroup.hpp>	// (vcl)
#include <Vcl.SysStyles.hpp>	// (vcl)
#include <Vcl.Styles.hpp>	// (vcl)
#include <BrandingAPI.hpp>	// (designide)
#include <PercentageDockTree.hpp>	// (designide)
#include <Vcl.Buttons.hpp>	// (vcl)
#include <Vcl.ExtDlgs.hpp>	// (vcl)
#include <Winapi.Mapi.hpp>	// (rtl)
#include <Vcl.ExtActns.hpp>	// (vcl)
#include <Vcl.ActnMenus.hpp>	// (vclactnband)
#include <Vcl.ActnMan.hpp>	// (vclactnband)
#include <Vcl.PlatformDefaultStyleActnCtrls.hpp>	// (vclactnband)
#include <Winapi.GDIPOBJ.hpp>	// (rtl)
#include <BaseDock.hpp>	// (designide)
#include <DeskUtil.hpp>	// (designide)
#include <DeskForm.hpp>	// (designide)
#include <DockForm.hpp>	// (designide)
#include <Xml.Win.msxmldom.hpp>	// (xmlrtl)
#include <Xml.xmldom.hpp>	// (xmlrtl)
#include <ToolsAPI.hpp>	// (designide)
#include <Proxies.hpp>	// (designide)
#include <DesignEditors.hpp>	// (designide)
#include <Vcl.Imaging.pngimage.hpp>	// (vclimg)
#include <frxChm.hpp>	// (frx26)
#include <fs_iconst.hpp>	// (fs26)
#include <frxRes.hpp>	// (frx26)
#include <fs_itools.hpp>	// (fs26)
#include <fs_iinterpreter.hpp>	// (fs26)
#include <frxDsgnIntf.hpp>	// (frx26)
#include <frxDMPClass.hpp>	// (frx26)
#include <frxStorage.hpp>	// (frx26)
#include <frxPrinter.hpp>	// (frx26)
#include <frxSearchDialog.hpp>	// (frx26)
#include <Vcl.OleCtnrs.hpp>	// (vcl)
#include <frxRichEdit.hpp>	// (frx26)
#include <frxUnicodeCtrls.hpp>	// (frx26)
#include <frxInPlaceClipboards.hpp>	// (frx26)
#include <frxInPlaceEditors.hpp>	// (frx26)
#include <frxIOTransportIntf.hpp>	// (frx26)
#include <frxIOTransportDialog.hpp>	// (frx26)
#include <frxPreview.hpp>	// (frx26)
#include <frxGraphicUtils.hpp>	// (frx26)
#include <frxrcClass.hpp>	// (frx26)
#include <fs_iclassesrtti.hpp>	// (fs26)
#include <fs_igraphicsrtti.hpp>	// (fs26)
#include <fs_iformsrtti.hpp>	// (fs26)
#include <Vcl.Imaging.jpeg.hpp>	// (vclimg)
#include <frxClassRTTI.hpp>	// (frx26)
#include <fs_ipascal.hpp>	// (fs26)
#include <fs_icpp.hpp>	// (fs26)
#include <fs_ibasic.hpp>	// (fs26)
#include <fs_ijs.hpp>	// (fs26)
#include <fs_idialogsrtti.hpp>	// (fs26)
#include <fs_iinirtti.hpp>	// (fs26)
#include <frxClass.hpp>	// (frx26)
#include <frxNetUtils.hpp>	// (frx26)
#include <frxMapHelpers.hpp>	// (frx26)
#include <IdGlobal.hpp>	// (IndySystem)
#include <IdWinsock2.hpp>	// (IndySystem)
#include <IdWship6.hpp>	// (IndySystem)
#include <IdIDN.hpp>	// (IndySystem)
#include <IdStackWindows.hpp>	// (IndySystem)
#include <IdStack.hpp>	// (IndySystem)
#include <IdComponent.hpp>	// (IndySystem)
#include <IdIOHandler.hpp>	// (IndyCore)
#include <IdIOHandlerStack.hpp>	// (IndyCore)
#include <IdThread.hpp>	// (IndyCore)
#include <IdSSL.hpp>	// (IndyProtocols)
#include <IdGlobalProtocols.hpp>	// (IndyProtocols)
#include <IdFTPListParseBase.hpp>	// (IndyProtocols)
#include <IdFIPS.hpp>	// (IndyProtocols)
#include <IdFTPListParseAS400.hpp>	// (IndyProtocols)
#include <IdFTPListParseBullGCOS7.hpp>	// (IndyProtocols)
#include <IdFTPListParseBullGCOS8.hpp>	// (IndyProtocols)
#include <IdFTPListParseChameleonNewt.hpp>	// (IndyProtocols)
#include <IdFTPListParseCiscoIOS.hpp>	// (IndyProtocols)
#include <IdFTPListParseDistinctTCPIP.hpp>	// (IndyProtocols)
#include <IdFTPListParseEPLF.hpp>	// (IndyProtocols)
#include <IdFTPListParseNovellNetware.hpp>	// (IndyProtocols)
#include <IdFTPListParseHellSoft.hpp>	// (IndyProtocols)
#include <IdFTPListParseIEFTPGateway.hpp>	// (IndyProtocols)
#include <IdFTPListParseKA9Q.hpp>	// (IndyProtocols)
#include <IdFTPListParseMicrowareOS9.hpp>	// (IndyProtocols)
#include <IdFTPListParseMPEiX.hpp>	// (IndyProtocols)
#include <IdFTPListParseMusic.hpp>	// (IndyProtocols)
#include <IdFTPListParseMVS.hpp>	// (IndyProtocols)
#include <IdFTPListParseNCSAForDOS.hpp>	// (IndyProtocols)
#include <IdFTPListParseNCSAForMACOS.hpp>	// (IndyProtocols)
#include <IdFTPListParseNovellNetwarePSU.hpp>	// (IndyProtocols)
#include <IdFTPListParseOS2.hpp>	// (IndyProtocols)
#include <IdFTPListParsePCNFSD.hpp>	// (IndyProtocols)
#include <IdFTPListParsePCTCP.hpp>	// (IndyProtocols)
#include <IdFTPListParseStercomOS390Exp.hpp>	// (IndyProtocols)
#include <IdFTPListParseStercomUnixEnt.hpp>	// (IndyProtocols)
#include <IdFTPListParseStratusVOS.hpp>	// (IndyProtocols)
#include <IdFTPListParseSuperTCP.hpp>	// (IndyProtocols)
#include <IdFTPListParseTandemGuardian.hpp>	// (IndyProtocols)
#include <IdFTPListParseTOPS20.hpp>	// (IndyProtocols)
#include <IdFTPListParseTSXPlus.hpp>	// (IndyProtocols)
#include <IdFTPListParseUnisysClearPath.hpp>	// (IndyProtocols)
#include <IdFTPListParseUnix.hpp>	// (IndyProtocols)
#include <IdFTPListParseVM.hpp>	// (IndyProtocols)
#include <IdFTPListParseVMS.hpp>	// (IndyProtocols)
#include <IdFTPListParseVSE.hpp>	// (IndyProtocols)
#include <IdFTPListParseVxWorks.hpp>	// (IndyProtocols)
#include <IdFTPListParseWfFTP.hpp>	// (IndyProtocols)
#include <IdFTPListParseWindowsNT.hpp>	// (IndyProtocols)
#include <IdFTPListParseWinQVTNET.hpp>	// (IndyProtocols)
#include <IdFTPListParseXecomMicroRTOS.hpp>	// (IndyProtocols)
#include <frxIOTransportFTP.hpp>	// (frxIntIOIndy26)
#include <Vcl.AxCtrls.hpp>	// (vcl)
#include <Vcl.OleCtrls.hpp>	// (vcl)
#include <frxFPUMask.hpp>	// (frxIntIOBase26)
#include <Vcl.OleServer.hpp>	// (vcl)
#include <SHDocVw.hpp>	// (vclie)
#include <frxSaveFilterBrowser.hpp>	// (frxIntIOBase26)
#include <System.JSON.hpp>	// (rtl)
#include <IdCoderMIME.hpp>	// (IndyProtocols)
#include <IdAuthentication.hpp>	// (IndyProtocols)
#include <IdHTTPHeaderInfo.hpp>	// (IndyProtocols)
#include <IdHeaderCoderBase.hpp>	// (IndyProtocols)
#include <IdHeaderCoderPlain.hpp>	// (IndyProtocols)
#include <IdHeaderCoder2022JP.hpp>	// (IndyProtocols)
#include <IdHeaderCoderIndy.hpp>	// (IndyProtocols)
#include <IdSSLOpenSSLHeaders.hpp>	// (IndyProtocols)
#include <IdSSLOpenSSL.hpp>	// (IndyProtocols)
#include <IdAuthenticationNTLM.hpp>	// (IndyProtocols)
#include <IdAuthenticationSSPI.hpp>	// (IndyProtocols)
#include <IdAuthenticationDigest.hpp>	// (IndyProtocols)
#include <IdLogBase.hpp>	// (IndyCore)
// PRG_EXT: .bpl
// OBJ_EXT: .obj

//-- user supplied -----------------------------------------------------------

namespace Dclfrxintioindy26
{
//-- forward type declarations -----------------------------------------------
//-- type declarations -------------------------------------------------------
//-- var, const, procedure ---------------------------------------------------
}	/* namespace Dclfrxintioindy26 */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_DCLFRXINTIOINDY26)
using namespace Dclfrxintioindy26;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// Dclfrxintioindy26HPP
